version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./web:/web
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm
        volumes:
            - ./web:/web
        links:
            - db
            - redis
    redis:
        image: redis
        ports:
            - '6379:6379'
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=myapp
        ports:
            - '8989:3306'
        volumes:
            - './data/db/mysql:/var/lib/mysql'

